linters-settings:
  govet:
    enable-all: true
    disable:
      - shadow
  revive:
    confidence: 0.8
  gocyclo:
    min-complexity: 20
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  depguard:
    rules:
      main:
        files:
          - $all
          - "!$test"
        allow:
          - $gostd
          - github.com/fsnotify/fsnotify
          - github.com/blackorder/reloader
  misspell:
    locale: US
  unparam:
    check-exported: false
  nakedret:
    max-func-lines: 30
  prealloc:
    simple: true
    range-loops: true
    for-loops: false
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
      - nestingReduce

linters:
  disable-all: true
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - gochecknoinits
    - goconst
    - gocritic
    - gofmt
    - goimports
    - mnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - revive
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - errname
    - errorlint
    - copyloopvar
    - forcetypeassert
    - gomoddirectives
    - importas
    - nilnil
    - usetesting

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - mnd
        - goconst
        - gosec
        - errname
        - forcetypeassert
        - usetesting
    - path: example.*\.go
      linters:
        - errcheck

run:
  timeout: 5m
